### ISSUE TITLE
AttributeError: 'module' object has no attribute 'APIClient'

### ISSUE THREAD

**Issue by popstas** [metacloud/molecule#771]
# Issue Type
- Bug report

# Molecule and Ansible details

```
molecule 1.21.0
docker-py 1.10.6
```

Appears today, after molecule update.

```
$ molecule test
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 94, in test
    t = Test(ctx.obj.get('args'), command_args)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/base.py", line 60, in __init__
    self.main()
  File "/usr/local/lib/python2.7/site-packages/molecule/command/base.py", line 83, in main
    self.molecule.main()
  File "/usr/local/lib/python2.7/site-packages/molecule/core.py", line 56, in main
    self.driver = self._get_driver()
  File "/usr/local/lib/python2.7/site-packages/molecule/core.py", line 298, in _get_driver
    return dockerdriver.DockerDriver(self)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 39, in __init__
    self._docker = docker.APIClient(
AttributeError: 'module' object has no attribute 'APIClient'
```

**Comment by alvaroaleman** [comment]
The underlying issue is the docker-py python module, which is now called `docker` and has an incompatible api.

If you remove the docker-py python module from your system and install the docker module instead, the issue should be gone.

**Comment by popstas** [comment]
@alvaroaleman, thank you!

**Comment by retr0h** [comment]
@popstas sorry about that.  We updated our docs, however, I am running into an issue with readthedocs building our docs.

**Comment by retr0h** [comment]
Documentation has now been posted to readthedocs.

* [CHANGELOG](http://molecule.readthedocs.io/en/stable-1.21/changelog.html#breaking-changes)
* [Quick Start](http://molecule.readthedocs.io/en/stable-1.21/index.html#quick-start)

**Comment by noydhiet** [comment]
Hi, I'm still facing the same issue.
```
sudo molecule test
Password:
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/command/test.py", line 94, in test
    t = Test(ctx.obj.get('args'), command_args)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/command/base.py", line 60, in __init__
    self.main()
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/command/base.py", line 83, in main
    self.molecule.main()
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/core.py", line 57, in main
    self.driver = self._get_driver()
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/core.py", line 312, in _get_driver
    return dockerdriver.DockerDriver(self)
  File "/usr/local/Cellar/molecule/1.25.1/libexec/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 39, in __init__
    self._docker = docker.APIClient(
AttributeError: 'module' object has no attribute 'APIClient'
```
I already tried to uninstall and install the python, remove the docker, install again, tried `pip install molecule` and everything remains the same.

Need advice
